M48
; DRILL file {KiCad 8.0.8} date 2025-01-29T22:29:30+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-29T22:29:30+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X1.8701Y-2.4038
X1.8764Y-1.3717
X2.652Y-1.3717
X2.9309Y-2.4038
M30
